name: Run Git Action tests

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        group: [ 1, 2 ]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run pytest
        run: pytest --splits 2 --group ${{ matrix.group }}